# Generated by Django 4.0.5 on 2022-06-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_details',
            name='guest_signature',
            field=models.FileField(upload_to='guest_signature'),
        ),
        migrations.AlterField(
            model_name='trip_details',
            name='total_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
