# Generated by Django 4.0.5 on 2022-06-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_trip_details_guest_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_details',
            name='total_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
