# Generated by Django 4.0.5 on 2022-06-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_trip_details_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_details',
            name='total_days',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip_details',
            name='total_time',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
