# Generated by Django 4.0.5 on 2022-06-17 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_trip_details_total_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=1024)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.driver')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trip_details')),
            ],
        ),
    ]
