# Generated by Django 4.0.5 on 2022-06-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip_details',
            old_name='review',
            new_name='remark',
        ),
    ]
