# Generated by Django 4.0.5 on 2022-06-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_review_trip_details_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_details',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='trip_details',
            name='remark',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
