# Generated by Django 4.0.5 on 2022-06-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_trip_details_address_alter_trip_details_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_details',
            name='all_routes',
            field=models.CharField(default=1, max_length=3500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='route',
        ),
    ]
